# Generated by Django 3.1.2 on 2021-04-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0002_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='autorized',
            field=models.BooleanField(default=False),
        ),
    ]
